package sshd

// The keyword list is derived from the sshd_config(5) manual page of OpenSSH
// portable (entries marked ".It Cm") plus keywords added by common
// distribution patches (GSSAPI key exchange). Extend it when a rule needs a
// keyword that is missing.

// knownKeywords are the lower-cased keywords kept in the snapshot.
// Directives with other keywords are counted but their arguments are
// discarded, so an Include that pulls in an unrelated file cannot copy its
// content into reports or snapshots.
var knownKeywords = map[string]bool{
	"acceptenv":                       true,
	"addressfamily":                   true,
	"allowagentforwarding":            true,
	"allowgroups":                     true,
	"allowstreamlocalforwarding":      true,
	"allowtcpforwarding":              true,
	"allowusers":                      true,
	"authenticationmethods":           true,
	"authorizedkeyscommand":           true,
	"authorizedkeyscommanduser":       true,
	"authorizedkeysfile":              true,
	"authorizedprincipalscommand":     true,
	"authorizedprincipalscommanduser": true,
	"authorizedprincipalsfile":        true,
	"banner":                          true,
	"casignaturealgorithms":           true,
	"channeltimeout":                  true,
	"chrootdirectory":                 true,
	"ciphers":                         true,
	"clientalivecountmax":             true,
	"clientaliveinterval":             true,
	"compression":                     true,
	"denygroups":                      true,
	"denyusers":                       true,
	"disableforwarding":               true,
	"exposeauthinfo":                  true,
	"fingerprinthash":                 true,
	"forcecommand":                    true,
	"gatewayports":                    true,
	"gssapiauthentication":            true,
	"gssapicleanupcredentials":        true,
	"gssapidelegatecredentials":       true,
	"gssapikexalgorithms":             true,
	"gssapikeyexchange":               true,
	"gssapistorecredentialsonrekey":   true,
	"gssapistrictacceptorcheck":       true,
	"hostbasedacceptedalgorithms":     true,
	"hostbasedauthentication":         true,
	"hostbasedusesnamefrompacketonly": true,
	"hostcertificate":                 true,
	"hostkey":                         true,
	"hostkeyagent":                    true,
	"hostkeyalgorithms":               true,
	"ignorerhosts":                    true,
	"ignoreuserknownhosts":            true,
	"ipqos":                           true,
	"kbdinteractiveauthentication":    true,
	"kerberosauthentication":          true,
	"kerberosgetafstoken":             true,
	"kerberosorlocalpasswd":           true,
	"kerberosticketcleanup":           true,
	"kexalgorithms":                   true,
	"listenaddress":                   true,
	"logingracetime":                  true,
	"loglevel":                        true,
	"logverbose":                      true,
	"macs":                            true,
	"maxauthtries":                    true,
	"maxsessions":                     true,
	"maxstartups":                     true,
	"modulifile":                      true,
	"pamservicename":                  true,
	"passwordauthentication":          true,
	"permitemptypasswords":            true,
	"permitlisten":                    true,
	"permitopen":                      true,
	"permitrootlogin":                 true,
	"permittty":                       true,
	"permittunnel":                    true,
	"permituserenvironment":           true,
	"permituserrc":                    true,
	"persourcemaxstartups":            true,
	"persourcenetblocksize":           true,
	"persourcepenalties":              true,
	"persourcepenaltyexemptlist":      true,
	"pidfile":                         true,
	"port":                            true,
	"printlastlog":                    true,
	"printmotd":                       true,
	"pubkeyacceptedalgorithms":        true,
	"pubkeyauthentication":            true,
	"pubkeyauthoptions":               true,
	"rdomain":                         true,
	"refuseconnection":                true,
	"rekeylimit":                      true,
	"requiredrsasize":                 true,
	"revokedkeys":                     true,
	"securitykeyprovider":             true,
	"setenv":                          true,
	"sshdauthpath":                    true,
	"sshdsessionpath":                 true,
	"streamlocalbindmask":             true,
	"streamlocalbindunlink":           true,
	"strictmodes":                     true,
	"subsystem":                       true,
	"syslogfacility":                  true,
	"tcpkeepalive":                    true,
	"trustedusercakeys":               true,
	"unusedconnectiontimeout":         true,
	"usedns":                          true,
	"usepam":                          true,
	"versionaddendum":                 true,
	"x11displayoffset":                true,
	"x11forwarding":                   true,
	"x11uselocalhost":                 true,
	"xauthlocation":                   true,
}
