package integration

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mrAndMistersTunguice/security-baseline-auditor/internal/rules"
)

// TestRulesDocumentationIsCurrent regenerates docs/rules.md from the rule
// catalog so the published rule reference cannot drift from the code.
// Run `go test ./tests/integration -update` after changing a rule.
func TestRulesDocumentationIsCurrent(t *testing.T) {
	var b bytes.Buffer
	b.WriteString("# Rule reference\n\n")
	b.WriteString("<!-- Generated by tests/integration/docs_test.go from the rule catalog. Do not edit by hand. -->\n\n")
	b.WriteString("Every rule evaluates only the normalized snapshot. A rule returns SKIP when the data it needs ")
	b.WriteString("could not be collected (unsupported platform, component not installed, insufficient privileges) ")
	b.WriteString("and ERROR when collection or evaluation failed unexpectedly. None of these rules claims ")
	b.WriteString("conformance with CIS Benchmarks or any other standard.\n\n")

	b.WriteString("| ID | Severity | Platforms | Title |\n|----|----------|-----------|-------|\n")
	for _, r := range rules.Builtin() {
		fmt.Fprintf(&b, "| [%s](#%s) | %s | %s | %s |\n", r.ID, strings.ToLower(r.ID), r.Severity, strings.Join(r.Platforms, ", "), r.Title)
	}
	for _, r := range rules.Builtin() {
		fmt.Fprintf(&b, "\n## %s\n\n", r.ID)
		fmt.Fprintf(&b, "**%s**\n\n", r.Title)
		fmt.Fprintf(&b, "- Category: %s\n- Severity: %s\n- Platforms: %s\n\n", r.Category, r.Severity, strings.Join(r.Platforms, ", "))
		fmt.Fprintf(&b, "%s\n\n", r.Description)
		fmt.Fprintf(&b, "*Why %s:* %s\n\n", r.Severity, r.SeverityRationale)
		fmt.Fprintf(&b, "*Remediation:* %s\n", r.Remediation)
		if len(r.References) > 0 {
			b.WriteString("\n*References:*\n\n")
			for _, ref := range r.References {
				fmt.Fprintf(&b, "- <%s>\n", ref)
			}
		}
	}
	golden(t, filepath.Join("..", "..", "docs", "rules.md"), b.Bytes())
}
